[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Radu Suciu", email = "radusuciu@gmail.com"},
]
dependencies = [
    "django>=4.2",
    "django-huey>=1.1.1",
    "redis>=4.5.4",
    "psycopg2>=2.9.6",
]
requires-python = ">=3.10"
license = {text = "MIT"}
